title: May 小阿姨烘培坊
tagline: Auntie May Bakery
description: 為了家人與自己的健康一頭栽入了烘焙世界，多年來堅持以單純無害的原料手工製作各類中西式點心。不使用花俏的化學食材、不需要過度的調味調色，用最簡單的好原料就能做出令人難以忘懷的口味。在親朋好友多年的支持與鼓勵之下，我們以做出讓人幸福滿滿的點心為宗旨，成立 May 小阿姨烘焙坊，希望將我們簡單好吃的好東西分享給更多人。
author: https://tsoliangwu.com
lang: zh-Hans-TW
logo: /assets/img/site-image.png
image: /assets/img/site-image.png

baseurl:
url: https://github.com/auntie-may-bakery/auntie-may-bakery.github.io

facebook:
  publisher: https://www.facebook.com/AuntieMayBakery/

twitter:
  card: summary

social:
  name: May 小阿姨烘培坊
  links:
    - https://www.facebook.com/AuntieMayBakery

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/site-image.png

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
syntax_highlighter: rouge
exclude: ['README.md']
permalink: pretty
sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
