title: May 小阿姨烘培坊
tagline: Auntie May Bakery
description: TBD
author: https://tsoliangwu.com
lang: zh-Hans-TW
logo: /assets/img/site-image.png
image: /assets/img/site-image.png

baseurl:
url: https://github.com/auntie-may-bakery/auntie-may-bakery.github.io

facebook:
  publisher: https://www.facebook.com/AuntieMayBakery/

twitter:
  card: summary

social:
  name: May 小阿姨烘培坊
  links:
    - https://www.facebook.com/AuntieMayBakery/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/site-image.png

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
syntax_highlighter: rouge
exclude: ['README.md']
permalink: pretty
sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
